openapi: '3.0.3'
info:
  title: MediMemo API
  version: '1.0'
servers:
  - url: https://localhost:3000/v1
paths:
  /login:
    post:
      tags:
        - login
      responses:
        '200':
          description: OK
  /user:
    get:
      tags:
        - user
      description: 'Get user profile'
      responses:
        '200':
          description: OK
    put:
      tags:
        - user
      description: 'Modify user profile'
      parameters: []
      responses:
        '200':
          description: OK

  /doses:
    get:
      tags:
        - reminders
      description: 'Returns the list of today reminders (related to PrescriptionTime)'
      parameters: []
      responses:
        '200':
          description: OK
  /doses/{id}:
    put:
      tags:
        - reminders
      description: 'Allows to save a new therapy'
      parameters: []
      responses:
        '200':
          description: OK
  /therapies:
    get:
      tags:
        - therapy
      description: 'Returns therapies of current user'
      parameters: []
      responses:
        '200':
          description: OK
    post:
      tags:
        - therapy
      description: 'Save a new therapy'
      parameters: []
      responses:
        '200':
          description: OK
  /therapies/{id}:
    get:
      tags:
        - therapy
      description: 'Returns a therapy and its prescriptions'
      parameters: []
      responses:
        '200':
          description: OK
    put:
      tags:
        - therapy
      description: 'Change a therapy'
      parameters: []
      responses:
        '200':
          description: OK
    delete:
      tags:
        - therapy
      description: 'Remove a therapy'
      parameters: []
      responses:
        '200':
          description: OK
  /therapies/{therapyId}/prescriptions:
    get:
      tags:
        - therapy
      description: 'Return prescriptions associated to a therapy'
      parameters: []
      responses:
        '200':
          description: OK
    post:
      tags:
        - therapy
      description: 'Save a new prescription related to a therapy'
      parameters: []
      responses:
        '200':
          description: OK
  /prescriptions/{id}:
    get:
      tags:
        - therapy
      description: ''
      parameters: []
      responses:
        '200':
          description: OK
    put:
      tags:
        - therapy
      description: 'Modify a prescription'
      parameters: []
      responses:
        '200':
          description: OK
    delete:
      tags:
        - therapy
      description: 'Remove a prescription'
      parameters: []
      responses:
        '200':
          description: OK
  /prescriptions/{id}/prescription-times:
    get:
      tags:
        - therapy
      description: 'Return prescriotion times of a prescription'
      parameters: []
      responses:
        '200':
          description: OK
    post:
      tags:
        - therapy
      description: 'Save a new prescription time related to a prescription'
      parameters: []
      responses:
        '200':
          description: OK
  /prescription-times/{id}:
    put:
      tags:
        - therapy
      description: 'Modify a prescription time'
      parameters: []
      responses:
        '200':
          description: OK
    delete:
      tags:
        - therapy
      description: 'Remove a prescription time'
      parameters: []
      responses:
        '200':
          description: OK
  /medicines:
    get:
      tags:
        - medicine
      description: 'Return a list of all medicines'
      parameters: []
      responses:
        '200':
          description: OK
  /medicines/{id}:
    get:
      tags:
        - medicine
      description: 'Return leaflet of a medicine'
      parameters: []
      responses:
        '200':
          description: OK
  /contacts:
    get:
      tags:
        - contacts
      description: 'Returns list of doctors'
      parameters: []
      responses:
        '200':
          description: OK
    post:
      tags:
        - contacts
      description: 'Add a new doctor'
      parameters: []
      responses:
        '200':
          description: OK
  /contacts/{id}:
    get:
      tags:
        - contacts
      description: Return doctor's details
      parameters: []
      responses:
        '200':
          description: OK
    put:
      tags:
        - contacts
      description: 'Modify a doctor'
      parameters: []
      responses:
        '200':
          description: OK
    delete:
      tags:
        - contacts
      description: 'Remove a doctor'
      parameters: []
      responses:
        '200':
          description: OK

          
  
